DROP TABLE IF EXISTS users, categories, locations, events, compilations,
participation_requests, comments, compilations_events;

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(250) NOT NULL,
    email   VARCHAR(254) NOT NULL,
    CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL,
    CONSTRAINT uq_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS locations (
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat         REAL NOT NULL,
    lon         REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    event_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    initiator_user_id     BIGINT                      NOT NULL,
    category_id           BIGINT                      NOT NULL,
    location_id           BIGINT                      NOT NULL,
    title                 VARCHAR(120)                NOT NULL,
    annotation            VARCHAR(2000)               NOT NULL,
    description           VARCHAR(7000)               NOT NULL,
    state                 VARCHAR(60)                 NOT NULL,
    date                  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    create_date           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    publish_date          TIMESTAMP WITHOUT TIME ZONE,
    participant_limit     INTEGER DEFAULT 0,
    is_paid               BOOLEAN DEFAULT FALSE,
    is_request_moderation BOOLEAN DEFAULT FALSE,

    CONSTRAINT fk_event_initiator FOREIGN KEY (initiator_user_id) REFERENCES users (user_id),
    CONSTRAINT fk_event_category FOREIGN KEY (category_id) REFERENCES categories (category_id),
    CONSTRAINT fk_event_location FOREIGN KEY (location_id) REFERENCES locations (location_id)
);

CREATE TABLE IF NOT EXISTS participation_requests (
    participation_request_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participation_user_id  BIGINT                              NOT NULL,
    participation_event_id BIGINT                              NOT NULL,
    status                         VARCHAR(60)                 NOT NULL,
    created_date                   TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT fk_participation_request_requester FOREIGN KEY (participation_user_id) REFERENCES users (user_id),
    CONSTRAINT fk_participation_request_event FOREIGN KEY (participation_event_id) REFERENCES events (event_id),
    CONSTRAINT uc_unique_requester_event UNIQUE (participation_user_id, participation_event_id)
);

CREATE TABLE IF NOT EXISTS compilations (
    compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(255) NOT NULL,
    is_pinned      BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations_events (
    compilation_id BIGINT,
    event_id       BIGINT,

    CONSTRAINT fk_compilation_id FOREIGN KEY (compilation_id) REFERENCES compilations (compilation_id),
    CONSTRAINT fk_event_id FOREIGN KEY (event_id) REFERENCES events (event_id),

    PRIMARY KEY (compilation_id, event_id)
);
